### ISSUE TITLE
This component is blacklisted on HACS

### ISSUE THREAD

**Issue by mdegat01** [custom-components/places#18]
I use this component and would like to keep using this component but I am concerned that it was blacklisted.  The blacklist is [here](https://github.com/hacs/default/blob/master/blacklist). If this is still being maintained please get it removed from the blacklist.

**Comment by tenly2000** [comment]
I just checked the blacklist.  It looks like the “tenly2000/places.py” is blacklisted (as it should be) because it is no longer being maintained by “tenly2000” (me).  The official, current version of the places.py component can be found at BC https://github.com/custom-components/places and from what I can see - it’s not in the blacklist.
