### ISSUE TITLE
documentations examples for template in github

### ISSUE THREAD

**Issue by axerontios** [custom-components/places#34]
This is great stuff you are sharing. I got it working easily. Though the struggle is real in regards to templating out some attributes out of the original sensor. 

- platform: template
  sensors:
    cargps:
      friendly_name: "car_GPS"
      icon_template: mdi-car-info
      value_template: "{{state_attr(sensor.place, Street) }}"
      
I did read the article below, though i still did not manage to get it working.

https://www.home-assistant.io/docs/configuration/templating/

Not sure if that is a json template that i should use, if yes how :/

All im trying to do is create a template sensor that will only have street &/or postal_code. So i can then + it into a lovelace card.

I realize this is more about templating in HomeAssistant rather this custom component  though i believe other folks will have the same struggle. So an example of a template or two in github would help a lot.     

In any case thanks for this custom component ! this is great work !!

**Comment by jdwhite** [comment]
Agreed that this isn't a place for a templating tutorial and that the issue here is mostly a matter of syntax in your template. To that end, let me recommend that you experiment with template creation using the Template Editor located in the 'Template' tab under the Developer Tools. I've found it to be invaluable in template creation. Once your template works you can simply copy and paste it.

You don't mention what your error was, but if I enter what you posted for the `value_template` above, `{{state_attr(sensor.place, Street) }}`, into the template editor I get the error `UndefinedError: 'sensor' is undefined`.

Adding single quotes around the args and changing the 'S' in Street to lower case fixes the issue: `{{ state_attr('sensor.outback', 'street') }}`. Attribute names are case-sensitive. Without changing the case you'll get the value `null`.

**Comment by Snuffy2** [comment]
@axerontios were you able to sort out your templating issues?

**Comment by Snuffy2** [comment]
Please open a new issue if you need further assistance.
