### ISSUE TITLE
No yaml config anymore? Significant regress. Restore yaml setings please.

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#53]
The integration is moved to UI.
```
Once loaded, you need to remove the places sensors from your configuration.yaml
```
So you left no choice for users and they now cannot use the integration as a package which can commented, moved to another HA instance, copied to another HA instance?

And please do not say that developers HAVE NO OTHER CHOICE.
At least you can support a "yaml settings keep read from yaml, Ui settings edit in UI" if you want using UI so much.
Check some other integrations: if settings are imported from yaml - they are read-only; only UI-entered settings are available for changing in UI.

Great, now I need to repeat same api_key, same settings an several places - instead of defining them in ONE place and then using an anchor.
Cannot use my email as a secret.
Cannot use a source sensor for some entry (devicetracker_id) which is a `sensor` - instead I am obliged to use `person` & `device_tracker`.
Cannot specify a `scan_interval`.

Also, using UI is supposed to be convenient for users.
But scrolling this screen is kind of typing SMS on Ericcson T28:
![image](https://user-images.githubusercontent.com/71872483/191167133-6cd42af2-d999-4492-a3ef-d6dd9bbd18d9.png)

This is not a progress. You are following a bad trend.

**Comment by Snuffy2** [comment]
Will be continuing with the UI.

Happy to help resolve any further issues.

**Comment by ildar170975** [comment]
> Will be continuing with the UI.

Very bad.

**Comment by timcampos** [comment]
I know this won't change anything, but +1 to @ildar170975's comment.  This trend by HA to "move to the UI" is awkward and confusing at best.  It destroys community collaboration.  

<sigh> in a misguided attempt to improve adoption we are following the group think of a strategy that sounds good but is poorly considered. 

Back to the original issue - you could AT LEAST provide more documentation on how to configure using the new UI.  I couldn't find any. This issue was the best I could find.  

Back to debugging why half of my sensorlocations have failed since upgrading to 2.0 :-(

**Comment by ildar170975** [comment]
I have downgraded to the old YAML version on the main HA setup.
The brand-new UI version is only installed on the test HA setup.
This moving to UI w/o leaving a possibility to use yaml is a kind of disrespect of Community.
