### ISSUE TITLE
Add scan_interval 

### ISSUE THREAD

**Issue by eyalcha** [custom-components/places#76]
New version doesn't support scan_interval configuration via UI

**Comment by Snuffy2** [comment]
Despite there being an option for it, scan_interval was actually never implemented in the previous version either.

If there is interest in actually adding it, it could be added.

**Comment by eyalcha** [comment]
@Snuffy2 I am not sure what is the current rate, but it will be good to have the option to control the scan interval

**Comment by Snuffy2** [comment]
The more and more I dig into this, I'm having 2 issues:
1. Without using a coordinator, I'm struggling to find a way to have a configurable scan_interval time. There may be a way, but I've not found it yet. The commonly used SCAN_INTERVAL in the sensor.py is a constant and doesn't seem be user configurable.
2. I really don't think a user-adjustable scan_interval is really needed for this integration. The main way that the places sensor  updates is when the devicetracker_id changes. Every time it changes, the places sensor updates. The scan interval then runs during "quiet" times when the devicetracker_id isn't changing. Since the devicetracker_id isn't changing, the places sensor doesn't really update either, making the scan interval updates questionable if they're even really needed.

Let me know your thoughts.

I'm going to remove this from my planned v2.1 release.

**Comment by ildar170975** [comment]
> 2\. The main way that the places sensor  updates is when the devicetracker_id changes

Do you mean "when a state of the is devicetracker_id changed" or "when a state or any attribute of the is devicetracker_id changed" ?
